name: rclass-project
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scikit-learn
  - matplotlib
  - tensorflow        # conda-forge’s CPU build
  - sage               # SageMath from conda-forge
  - pip
  - pytest
  - pip:
      - gurobipy       # pip wheel only; license isn’t needed for import
