name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: rclass-project
          use-mamba: 
      - name: List installed packages
        run: conda list
      - name: Install package
        run: pip install -e .
      - name: Check sage import
        run: python -c "from sage.all import *; print('Sage imported successfully')"
      - name: Run smoke test
        run: python tests/smoke_test.py
      - name: Run unit tests
        run: pytest --maxfail=1 --disable-warnings -q